/**
 * © Vectorted 2026. All rights reserved.
 * This software or content is protected by copyright law and may not be
 * reproduced, distributed, or modified without permission.
 * 
 * GitHub: https://github.com/Vectorted
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_vector_client_VectortedModule */

#ifndef _Included_org_vector_client_VectortedModule
#define _Included_org_vector_client_VectortedModule
#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    waitProcess
 * Signature: (J)V
 * 
 * Waits for attached process to stop execution.
 * Must be called after attachProcess() and before memory operations.
 * Blocks until target process is fully suspended.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance
 * @param pid     Attached process ID
 * 
 * @throws IllegalStateException if process not attached
 * @throws ProcessWaitException if wait fails
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_waitProcess
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    attachProcess
 * Signature: (J)Z
 * 
 * Attaches debugger to target process for memory operations.
 * Must be called before any attachGetAddress() or attachSetValueFromAddress() calls.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param pid     Target process ID
 * 
 * @return JNI_TRUE if attachment successful, JNI_FALSE otherwise
 * 
 * @note Requires appropriate debug privileges on target process
 * @note Not reentrant - detachProcess() must be called before reattachment
 * 
 * @see #detachProcess(JNIEnv*, jobject, jlong)
 */
JNIEXPORT jboolean JNICALL Java_org_vector_client_VectortedModule_attachProcess
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    detachProcess
 * Signature: (J)Z
 * 
 * Detaches debugger from previously attached process.
 * Releases all handles and cleans up process resources.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param pid     Process ID to detach from
 * 
 * @return JNI_TRUE if detachment successful, JNI_FALSE otherwise
 * 
 * @note Should be called for every successful attachProcess() call
 * @note Failing to detach may cause resource leaks
 * 
 * @see #attachProcess(JNIEnv*, jobject, jlong)
 */
JNIEXPORT jboolean JNICALL Java_org_vector_client_VectortedModule_detachProcess
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    attachGetAddress
 * Signature: (JIJ)J
 * 
 * Reads memory value from specified address in attached process.
 * Process must be attached with attachProcess() before calling.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param pid     Attached process ID
 * @param size    Size of data to read in bytes (1, 2, 4, or 8)
 * @param address Target memory address in process
 * 
 * @return Read value as 64-bit integer
 * 
 * @throws IllegalArgumentException if size is not 1, 2, 4, or 8
 * @throws IllegalStateException if process not properly attached
 * @throws MemoryAccessException if address is invalid or inaccessible
 * 
 * @see #attachProcess(JNIEnv*, jobject, jlong)
 * @see #attachSetValueFromAddress(JNIEnv*, jobject, jlong, jint, jlong, jobject)
 */
JNIEXPORT jlong JNICALL Java_org_vector_client_VectortedModule_attachGetLongAddress
  (JNIEnv *, jobject, jlong, jint, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    attachSetValueFromAddress
 * Signature: (JIJLjava/lang/Object;)V
 * 
 * Writes value to memory address in attached process.
 * Process must be attached with attachProcess() before calling.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param pid     Attached process ID
 * @param size    Size of data to write in bytes (1, 2, 4, or 8)
 * @param address Target memory address in process
 * @param value   Value to write (Byte, Short, Integer, or Long)
 * 
 * @throws IllegalArgumentException if size doesn't match value type
 * @throws IllegalStateException if process not properly attached
 * @throws MemoryAccessException if address is invalid or read-only
 * 
 * @see #attachProcess(JNIEnv*, jobject, jlong)
 * @see #attachGetAddress(JNIEnv*, jobject, jlong, jint, jlong)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_attachSetValueFromAddress
  (JNIEnv *, jobject, jlong, jint, jlong, jobject);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    offsetof
 * Signature: (JJ)J
 * 
 * Calculates memory offset from base address.
 * Performs simple address arithmetic by adding byte offset to base address.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance
 * @param address Base memory address
 * @param offset  Byte offset to add
 * 
 * @return Resulting memory address (base + offset)
 * 
 * @note This is a low-level memory operation function
 * @note No bounds checking is performed
 * 
 * @see Java_org_vector_client_VectortedModule_attachGetAddress
 * @see Java_org_vector_client_VectortedModule_attachSetValueFromAddress
 */
JNIEXPORT jlong JNICALL Java_org_vector_client_VectortedModule_offsetof
  (JNIEnv *, jobject, jlong, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    toChar
 * Signature: (J)J
 * 
 * Converts a memory address to a char representation and returns as jlong.
 * Extracts character value from the specified memory address.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance
 * @param address Memory address to convert
 * 
 * @return Character value from the address, returned as jlong
 * 
 * @note This is a low-level memory operation function
 * @note No bounds checking is performed
 */
JNIEXPORT jchar JNICALL Java_org_vector_client_VectortedModule_toChar
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    toInt
 * Signature: (J)J
 * 
 * Converts a memory address to an int representation and returns as jlong.
 * Extracts integer value from the specified memory address.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance
 * @param address Memory address to convert
 * 
 * @return Integer value from the address, returned as jlong
 * 
 * @note This is a low-level memory operation function
 * @note No bounds checking is performed
 */
JNIEXPORT jint JNICALL Java_org_vector_client_VectortedModule_toInt
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    toFloat
 * Signature: (J)J
 * 
 * Converts a memory address to a float representation and returns as jlong.
 * Extracts floating-point value from the specified memory address.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance
 * @param address Memory address to convert
 * 
 * @return Floating-point value from the address, returned as jlong
 * 
 * @note This is a low-level memory operation function
 * @note No bounds checking is performed
 */
JNIEXPORT jfloat JNICALL Java_org_vector_client_VectortedModule_toFloat
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    toBoolean
 * Signature: (J)J
 * 
 * Converts a memory address to a boolean representation and returns as jlong.
 * Extracts boolean value from the specified memory address.
 * Non-zero value returns true, zero returns false.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance
 * @param address Memory address to convert
 * 
 * @return Boolean value from the address, returned as jlong
 * 
 * @note This is a low-level memory operation function
 * @note No bounds checking is performed
 */
JNIEXPORT jboolean JNICALL Java_org_vector_client_VectortedModule_toBoolean
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    toShort
 * Signature: (J)S
 * 
 * Converts a memory address to a short representation.
 * Extracts the lower 16 bits of the address and returns as jshort.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance
 * @param address Memory address to convert
 * 
 * @return 16-bit short value from the address
 * 
 * @note This is a low-level memory operation function
 * @note Address is masked with 0xFFFF to extract lower 16 bits
 */
JNIEXPORT jshort JNICALL Java_org_vector_client_VectortedModule_toShort
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    bindSlave
 * Signature: (Ljava/lang/String;I)V
 * 
 * Binds CS104 slave service to specified network endpoint.
 * Creates and configures slave service for IEC 60870-5-104 protocol communication.
 * Must be called before startSlaveService(). Overwrites existing slave_service.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param ip      IP address string ("0.0.0.0" for all interfaces)
 * @param port    TCP port number (standard: 2404)
 * 
 * @note Caller must ensure proper cleanup with stopSlaveService()
 * @note Not thread-safe due to global slave_service variable
 * 
 * @see #startSlaveService(JNIEnv*, jobject, jobject)
 * @see #stopSlaveService(JNIEnv*, jobject, jlong)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_bindSlave
  (JNIEnv *, jobject, jstring, jint);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    startSlaveService
 * Signature: (Ljava/lang/Object;)J
 * 
 * Starts CS104 slave service and creates worker thread.
 * Sets server mode, starts slave service, and creates detached thread for continuous operation.
 * Returns thread handle for later service control.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param handler Callback handler for worker thread (may be null)
 * @return        Thread handle as jlong, or 0 on failure
 * 
 * @note Requires prior successful call to bindSlave()
 * @note Creates detached thread that runs until slave_state becomes false
 * @note Always check return value for success (non-zero)
 * 
 * @see #bindSlave(JNIEnv*, jobject, jstring, jint)
 * @see #stopSlaveService(JNIEnv*, jobject, jlong)
 * @see #slave_worker(void*)
 */
JNIEXPORT jlong JNICALL Java_org_vector_client_VectortedModule_startSlaveService
  (JNIEnv *, jobject, jobject);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    stopSlaveService
 * Signature: (J)V
 * 
 * Stops CS104 slave service and cleans up resources.
 * Signals worker thread to stop, stops slave service, and releases all allocated resources.
 * Also cleans up JNI global references to prevent memory leaks.
 * 
 * @param env      JNI environment pointer
 * @param object   Java object instance (unused)
 * @param threadId Thread handle returned from startSlaveService()
 * 
 * @note Does nothing if threadId is 0 (invalid handle)
 * @note Safe to call multiple times (idempotent)
 * @note Sets slave_service to NULL after destruction to prevent double-free
 * 
 * @see #startSlaveService(JNIEnv*, jobject, jobject)
 * @see #bindSlave(JNIEnv*, jobject, jstring, jint)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_stopSlaveService
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    setSlaveValue
 * Signature: (JI)V
 * 
 * Sends scaled measured value ASDU to connected CS104 clients.
 * Creates and queues an IEC 60870-5-101/104 ASDU containing the specified value
 * for transmission to monitoring clients. Only processes valid module addresses.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param module  IEC 60870 module address in range [16385, 22879]
 * @param value   Scaled integer value to send (typically 16-bit signed)
 * 
 * @note Module address range corresponds to standard IEC 61850/IEC 60870 address space
 * @note Uses CS101_COT_PERIODIC cause of transmission for regular updates
 * @note Quality is set to IEC60870_QUALITY_GOOD (all flags clear)
 * @note Function is no-op if module address is outside valid range
 * @note Caller must ensure slave_service is properly initialized via bindSlave()
 * 
 * @warning Potential memory leak if CS101_ASDU_destroy() fails due to early return
 * 
 * @see CS101_ASDU_create
 * @see MeasuredValueScaled_create  
 * @see CS104_Slave_enqueueASDU
 * @see CS101_ASDU_destroy
 * @see InformationObject_destroy
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_sendSlaveBlock
  (JNIEnv *, jobject, jintArray, jfloat);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    getNodeList
 * Signature: ()Ljava/util/HashMap;
 * 
 * Retrieves the complete hierarchical data model from the MMS server.
 * This native method traverses all IEC 61850 data points in the server's model,
 * including logical devices, logical nodes, data objects, and data attributes,
 * returning their hierarchical structure as a Java HashMap.
 * 
 * @param env     JNI environment pointer - provides access to JNI functions
 * @param object  Java object instance - the calling VectortedModule instance
 * 
 * @return        HashMap<Integer, ArrayList<Object>> containing:
 *                - Key: Integer representing hierarchical depth (0=root/LD, 1=LN, 2=DO, 3=DA)
 *                - Value: ArrayList of Object arrays, each containing:
 *                  [0] String - Full data point path (e.g., "LD1/GGIO1.Ind1.stVal")
 *                  [1] String - Node name (e.g., "stVal")
 *                  [2] String - Description or functional constraint
 *                  [3] String - Node type ("LD", "LN", "DO", "DA", "SDO")
 * 
 * @throws        NullPointerException if server model is not initialized
 * @throws        RuntimeException     if native memory allocation fails or model traversal error occurs
 * 
 * @note          This method requires an active MMS server instance (bound via bind() method)
 * @note          The returned HashMap maintains insertion order (LinkedHashMap behavior in native code)
 * @note          Memory for the returned data structure is managed by JNI and will be garbage collected
 * @note          Large data models may take significant time to traverse (O(n) complexity)
 * 
 * @performance   Time complexity: O(n) where n = total data points in model
 * @performance   Space complexity: O(n) for the returned data structure
 * 
 * @see           #bind(JNIEnv*, jobject, jstring, jint)
 * @see           #setFloatValue(JNIEnv*, jobject, jstring, jfloat)
 * @see           #setBoolValue(JNIEnv*, jobject, jstring, jboolean)
 * @see           #setIntValue(JNIEnv*, jobject, jstring, jint)
 * 
 * @since         Version 1.0.0
 * @author        Vectorted Engineering
 * @copyright     © Vectorted 2026. All rights reserved.
 */
JNIEXPORT jobject JNICALL Java_org_vector_client_VectortedModule_getNodeList
  (JNIEnv *, jobject);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    bind
 * Signature: (Ljava/lang/String;I)V
 * 
 * Binds MMS server to specified network endpoint.
 * Creates IEC 61850 MMS server instance and starts listening for client connections.
 * Server will accept MMS protocol connections from engineering tools and SCADA systems.
 * 
 * @param env     JNI environment pointer
 * @param object  Java object instance (unused)
 * @param ip      IP address string for MMS server binding
 * @param port    TCP port number for MMS service (standard: 102)
 * 
 * @note Must be called before any MMS data operations
 * @note Overwrites existing service if called multiple times
 * @note IEC 61850 MMS typically uses port 102, but can be configured
 * 
 * @see #setFloatValue(JNIEnv*, jobject, jstring, jfloat)
 * @see #setBoolValue(JNIEnv*, jobject, jstring, jboolean)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_bind
  (JNIEnv *, jobject, jstring, jint);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    pointModel
 * Signature: (Ljava/lang/String;)V
 * 
 * Sets the physical file path for the IEC 61850 standard model.
 * This method must be called before binding the MMS server to configure the loading of the SCL model file compliant with IEC 61850.
 * 
 * @param env       JNI environment pointer
 * @param object    Java object instance (unused)
 * @param modelPath The complete local filesystem path to the IEC 61850 model file (typically .scd, .icd, or .cid format)
 * 
 * @note Must be called prior to the `bind` method to provide the necessary data model for the server.
 * @note The model file must conform to the IEC 61850 SCL (System Configuration Language) standard.
 * @note The path should be an absolute local path, including the filename and extension.
 * 
 * @see #bind(JNIEnv*, jobject, jstring, jint)
 * @see #setFloatValue(JNIEnv*, jobject, jstring, jfloat)
 * @see #setBoolValue(JNIEnv*, jobject, jstring, jboolean)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_pointModel
  (JNIEnv *, jobject, jstring);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    startService
 * Signature: (Ljava/lang/Object;)J
 * 
 * Starts background data processing service with worker thread.
 * Creates independent native thread that invokes handler callback at intervals
 * for real-time MMS data model maintenance and processing tasks.
 * 
 * @param env     JNI environment pointer  
 * @param object  Java object instance (unused)
 * @param handler Callback handler implementing worker thread operations
 * @return        Native thread handle as jlong, or 0 on failure
 * 
 * @note Handler must implement runTickOnWorkerThread(long) method
 * @note Return value must be stored for later service termination
 * @note Creates detached thread - cannot join, only signal stop
 * 
 * @see #stopService(JNIEnv*, jobject, jlong)
 * @see Handler#runTickOnWorkerThread(long)
 */
JNIEXPORT jlong JNICALL Java_org_vector_client_VectortedModule_startService
  (JNIEnv *, jobject, jobject);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    stopService
 * Signature: (J)V
 * 
 * Stops background data processing service and cleans up resources.
 * Signals worker thread to terminate, stops MMS server, and releases all allocated resources.
 * Should be called with handle returned from startService().
 * 
 * @param env        JNI environment pointer
 * @param object     Java object instance (unused)  
 * @param threadId   Thread handle returned from startService()
 * 
 * @note Safe to call with invalid handle (0 or already stopped)
 * @note Idempotent - multiple calls have same effect as single call
 * @note Ensures graceful thread termination and resource cleanup
 * 
 * @see #startService(JNIEnv*, jobject, jobject)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_stopService
  (JNIEnv *, jobject, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    setFloatValue
 * Signature: (Ljava/lang/String;F)V
 * 
 * Updates floating-point data attribute in IEC 61850 data model.
 * Locates data attribute by object reference path and sets its value
 * in the MMS server's data model for client access.
 * 
 * @param env                 JNI environment pointer
 * @param object              Java object instance (unused)
 * @param dataAttributePath  IEC 61850 object reference path (e.g., "IED1/LLN0.Measurement.AnalogueValue1")
 * @param value               Floating-point value to set (32-bit IEEE 754)
 * 
 * @note Path must follow IEC 61850 naming conventions and exist in model
 * @note Changes are immediately visible to connected MMS clients
 * @note Typical use: analog measurements, setpoints, calculated values
 * 
 * @throws May cause segmentation fault if path invalid or server not initialized
 * 
 * @see IedServer_updateFloatAttributeValue
 * @see #setBoolValue(JNIEnv*, jobject, jstring, jboolean)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_setFloatValue
  (JNIEnv *, jobject, jstring, jfloat);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    setIntValue
 * Signature: (Ljava/lang/String;I)V
 * 
 * Updates Int32 data attribute in IEC 61850 data model.
 * Locates data attribute by object reference path and sets its integer value
 * in the MMS server's data model for client access.
 * 
 * @param env                 JNI environment pointer
 * @param object              Java object instance (unused)
 * @param dataAttributePath  IEC 61850 object reference path (e.g., "IED1/LLN0.Measurement.AnalogueInput1")
 * @param value               Int32 value to set (range: -2147483648 to 2147483647)
 * 
 * @note Path must follow IEC 61850 naming conventions and exist in model
 * @note Changes are immediately visible to connected MMS clients  
 * @note Typical use: digital states, small counters, status codes, enum values
 * @note Value will be truncated if exceeds Int32 range limits
 * 
 * @throws May cause segmentation fault if path invalid or server not initialized
 * 
 * @see IedServer_updateInt32AttributeValue
 * @see #setBoolValue(JNIEnv*, jobject, jstring, jboolean)
 * @see #setLongValue(JNIEnv*, jobject, jstring, jlong)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_setIntValue
  (JNIEnv *, jobject, jstring, jint);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    setLongValue
 * Signature: (Ljava/lang/String;J)V
 * 
 * Updates Int64 data attribute in IEC 61850 data model.
 * Locates data attribute by object reference path and sets its 64-bit integer value
 * in the MMS server's data model for client access.
 * 
 * @param env                 JNI environment pointer
 * @param object              Java object instance (unused)
 * @param dataAttributePath  IEC 61850 object reference path (e.g., "IED1/LLN0.Measurement.TimestampValue")
 * @param value               Int64 value to set (range: -9223372036854775808 to 9223372036854775807)
 * 
 * @note Path must follow IEC 61850 naming conventions and exist in model
 * @note Changes are immediately visible to connected MMS clients  
 * @note Typical use: timestamps, large counters, file sizes, serial numbers
 * @note Suitable for values exceeding Int32 range limitations
 * 
 * @throws May cause segmentation fault if path invalid or server not initialized
 * 
 * @see IedServer_updateInt64AttributeValue
 * @see #setIntValue(JNIEnv*, jobject, jstring, jint)
 * @see #setBoolValue(JNIEnv*, jobject, jstring, jboolean)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_setLongValue
  (JNIEnv *, jobject, jstring, jlong);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    syncClientTime
 * Signature: (Ljava/lang/String;)V
 * 
 * Synchronizes client system time to IEC 61850 timestamp attribute.
 * Gets current UTC time and updates specified .t attribute for time sync.
 * 
 * @param env                 JNI environment pointer
 * @param object              Java object instance (unused)
 * @param address             IEC 61850 object reference path ending with .t
 * 
 * @note Uses Hal_getTimeInMs() for UTC time in milliseconds
 * @note Changes immediately visible to connected MMS clients
 * @note Path must exist in IED model and support timestamp type
 * 
 * @throws May cause segmentation fault if path invalid or server not initialized
 * 
 * @see IedServer_updateUTCTimeAttributeValue
 * @see Hal_getTimeInMs
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_syncClientTime
  (JNIEnv *, jobject, jstring);

/**
 * Class:     org_vector_client_VectortedModule
 * Method:    setBoolValue
 * Signature: (Ljava/lang/String;Z)V
 * 
 * Updates boolean data attribute in IEC 61850 data model.
 * Locates data attribute by object reference path and sets its logical value
 * in the MMS server's data model for client access.
 * 
 * @param env                 JNI environment pointer
 * @param object              Java object instance (unused)
 * @param dataAttributePath  IEC 61850 object reference path (e.g., "IED1/LLN0.Protection.GeneralInterlock")
 * @param value               Boolean value to set (true/false)
 * 
 * @note Path must follow IEC 61850 naming conventions and exist in model
 * @note Changes are immediately visible to connected MMS clients  
 * @note Typical use: digital inputs, status flags, control outputs
 * 
 * @throws May cause segmentation fault if path invalid or server not initialized
 * 
 * @see IedServer_updateBooleanAttributeValue
 * @see #setFloatValue(JNIEnv*, jobject, jstring, jfloat)
 */
JNIEXPORT void JNICALL Java_org_vector_client_VectortedModule_setBoolValue
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
