/*
 * This file was generated by the Gradle 'init' task.1
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("com.gradleup.shadow") version "9.3.1"
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(fileTree("../libs/jars/") {
        include("*.jar")
    })
    implementation(libs.v8Byte)
    implementation(libs.byteAgent)
    implementation(libs.guava)
    implementation(libs.json)
    implementation(libs.node)
    implementation(libs.v8)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named("shadowJar") {
    enabled = false
}

tasks.named<Jar>("jar") {
    archiveBaseName.set("Vectorted")
    archiveVersion.set("Sdk.v3")

    manifest {
        attributes(
            "Implementation-Title" to project.name,
            "Implementation-Version" to project.version,
            "Main-Class" to "org.vector.Application"
        )
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    from(configurations.runtimeClasspath.get().filter { it.exists() }.map { zipTree(it) })
    from(sourceSets.main.get().output)
    from("../libvectorted.so")
}

application {
    // Define the main class for the application.
    mainClass = "org.vector.Application"
}
